In [132]:
# !conda install -y numpy pandas

In [133]:
import duckdb
import pandas as pd

con = duckdb.connect("data/nearshift.duckdb", read_only=True)

In [134]:
con.execute("""
    SELECT table_schema, table_name
    FROM information_schema.tables
    ORDER BY table_schema, table_name
""").fetchdf()

   table_schema                         table_name
0       curated               category_performance
1       curated               customer_repeat_rate
2       curated               delivery_performance
3       curated                monthly_order_value
4       curated                      monthly_sales
5       modeled                      dim_customers
6       modeled                       dim_products
7       modeled                   fact_order_items
8       modeled                        fact_orders
9       modeled                      fact_payments
10          raw            olist_customers_dataset
11          raw          olist_geolocation_dataset
12          raw          olist_order_items_dataset
13          raw       olist_order_payments_dataset
14          raw        olist_order_reviews_dataset
15          raw               olist_orders_dataset
16          raw             olist_products_dataset
17          raw              olist_sellers_dataset
18          raw  product_category_name_translation

## olist_customers_dataset

In [135]:
con.execute("""
    SELECT *
    FROM raw.olist_customers_dataset
    LIMIT 5
""").fetchdf()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [136]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_customers_dataset
""").fetchdf()

    rows
0  99441

In [137]:
con.execute("""
    DESCRIBE raw.olist_customers_dataset
""").fetchdf()

                column_name column_type null   key default extra
0               customer_id     VARCHAR  YES  None    None  None
1        customer_unique_id     VARCHAR  YES  None    None  None
2  customer_zip_code_prefix     VARCHAR  YES  None    None  None
3             customer_city     VARCHAR  YES  None    None  None
4            customer_state     VARCHAR  YES  None    None  None

## olist_geolocation_dataset

In [138]:
con.execute("""
    SELECT *
    FROM raw.olist_geolocation_dataset
    LIMIT 5
""").fetchdf()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.54562128115268,-46.63929204800168,sao paulo,SP
1,01046,-23.546081127035535,-46.64482029837157,sao paulo,SP
2,01046,-23.54612896641469,-46.64295148361138,sao paulo,SP
3,01041,-23.5443921648681,-46.63949930627844,sao paulo,SP
4,01035,-23.541577961711493,-46.64160722329613,sao paulo,SP

In [139]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_geolocation_dataset
""").fetchdf()

      rows
0  1000163

In [140]:
con.execute("""
    DESCRIBE raw.olist_geolocation_dataset
""").fetchdf()

                   column_name column_type null   key default extra
0  geolocation_zip_code_prefix     VARCHAR  YES  None    None  None
1              geolocation_lat     VARCHAR  YES  None    None  None
2              geolocation_lng     VARCHAR  YES  None    None  None
3             geolocation_city     VARCHAR  YES  None    None  None
4            geolocation_state     VARCHAR  YES  None    None  None

## olist_order_items_dataset

In [141]:
con.execute("""
    SELECT *
    FROM raw.olist_order_items_dataset
    LIMIT 5
""").fetchdf()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [142]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_order_items_dataset
""").fetchdf()

     rows
0  112650

In [143]:
con.execute("""
    DESCRIBE raw.olist_order_items_dataset
""").fetchdf()

           column_name column_type null   key default extra
0             order_id     VARCHAR  YES  None    None  None
1        order_item_id     VARCHAR  YES  None    None  None
2           product_id     VARCHAR  YES  None    None  None
3            seller_id     VARCHAR  YES  None    None  None
4  shipping_limit_date     VARCHAR  YES  None    None  None
5                price     VARCHAR  YES  None    None  None
6        freight_value     VARCHAR  YES  None    None  None

## olist_order_payments_dataset

In [144]:
con.execute("""
    SELECT *
    FROM raw.olist_order_payments_dataset
    LIMIT 5
""").fetchdf()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [145]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_order_payments_dataset
""").fetchdf()

     rows
0  103886

In [146]:
con.execute("""
    DESCRIBE raw.olist_order_payments_dataset
""").fetchdf()

            column_name column_type null   key default extra
0              order_id     VARCHAR  YES  None    None  None
1    payment_sequential     VARCHAR  YES  None    None  None
2          payment_type     VARCHAR  YES  None    None  None
3  payment_installments     VARCHAR  YES  None    None  None
4         payment_value     VARCHAR  YES  None    None  None

## olist_order_reviews_dataset

In [147]:
con.execute("""
    SELECT *
    FROM raw.olist_order_reviews_dataset
    LIMIT 5
""").fetchdf()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,None,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,None,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [148]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_order_reviews_dataset
""").fetchdf()

    rows
0  99224

In [149]:
con.execute("""
    DESCRIBE raw.olist_order_reviews_dataset
""").fetchdf()

               column_name column_type null   key default extra
0                review_id     VARCHAR  YES  None    None  None
1                 order_id     VARCHAR  YES  None    None  None
2             review_score     VARCHAR  YES  None    None  None
3     review_comment_title     VARCHAR  YES  None    None  None
4   review_comment_message     VARCHAR  YES  None    None  None
5     review_creation_date     VARCHAR  YES  None    None  None
6  review_answer_timestamp     VARCHAR  YES  None    None  None

##  olist_orders_dataset

In [150]:
con.execute("""
    SELECT *
    FROM raw.olist_orders_dataset
    LIMIT 5
""").fetchdf()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [151]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_orders_dataset
""").fetchdf()

    rows
0  99441

In [152]:
con.execute("""
    DESCRIBE raw.olist_orders_dataset
""").fetchdf()

                     column_name column_type null   key default extra
0                       order_id     VARCHAR  YES  None    None  None
1                    customer_id     VARCHAR  YES  None    None  None
2                   order_status     VARCHAR  YES  None    None  None
3       order_purchase_timestamp     VARCHAR  YES  None    None  None
4              order_approved_at     VARCHAR  YES  None    None  None
5   order_delivered_carrier_date     VARCHAR  YES  None    None  None
6  order_delivered_customer_date     VARCHAR  YES  None    None  None
7  order_estimated_delivery_date     VARCHAR  YES  None    None  None

## olist_products_dataset

In [153]:
con.execute("""
    SELECT *
    FROM raw.olist_products_dataset
    LIMIT 5
""").fetchdf()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625,20,17,13

In [154]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_products_dataset
""").fetchdf()

    rows
0  32951

In [155]:
con.execute("""
    DESCRIBE raw.olist_products_dataset
""").fetchdf()

                  column_name column_type null   key default extra
0                  product_id     VARCHAR  YES  None    None  None
1       product_category_name     VARCHAR  YES  None    None  None
2         product_name_lenght     VARCHAR  YES  None    None  None
3  product_description_lenght     VARCHAR  YES  None    None  None
4          product_photos_qty     VARCHAR  YES  None    None  None
5            product_weight_g     VARCHAR  YES  None    None  None
6           product_length_cm     VARCHAR  YES  None    None  None
7           product_height_cm     VARCHAR  YES  None    None  None
8            product_width_cm     VARCHAR  YES  None    None  None

## olist_sellers_dataset

In [156]:
con.execute("""
    SELECT *
    FROM raw.olist_sellers_dataset
    LIMIT 5
""").fetchdf()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [157]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.olist_sellers_dataset
""").fetchdf()

   rows
0  3095

In [158]:
con.execute("""
    DESCRIBE raw.olist_sellers_dataset
""").fetchdf()

              column_name column_type null   key default extra
0               seller_id     VARCHAR  YES  None    None  None
1  seller_zip_code_prefix     VARCHAR  YES  None    None  None
2             seller_city     VARCHAR  YES  None    None  None
3            seller_state     VARCHAR  YES  None    None  None

## product_category_name_translation

In [159]:
con.execute("""
    SELECT *
    FROM raw.product_category_name_translation
    LIMIT 5
""").fetchdf()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [160]:
con.execute("""
    SELECT COUNT(*) AS rows
    FROM raw.product_category_name_translation
""").fetchdf()

   rows
0    71

In [161]:
con.execute("""
    DESCRIBE raw.product_category_name_translation
""").fetchdf()

                     column_name column_type null   key default extra
0          product_category_name     VARCHAR  YES  None    None  None
1  product_category_name_english     VARCHAR  YES  None    None  None

## Duplicates

In [162]:
con.execute("""
    SELECT order_id, COUNT(*) AS duplicates
    FROM raw.olist_orders_dataset
    GROUP BY order_id
    HAVING COUNT(*) > 1
""").fetchdf()

Empty DataFrame
Columns: [order_id, duplicates]
Index: []

In [163]:
con.execute("""
    SELECT order_id, order_item_id, COUNT(*) AS duplicates
    FROM raw.olist_order_items_dataset
    GROUP BY order_id, order_item_id
    HAVING COUNT(*) > 1;
""").fetchdf()

Empty DataFrame
Columns: [order_id, order_item_id, duplicates]
Index: []

In [164]:
con.execute("""
    SELECT order_id, payment_sequential, COUNT(*) AS duplicates
    FROM raw.olist_order_payments_dataset
    GROUP BY order_id, payment_sequential
    HAVING COUNT(*) > 1;
""").fetchdf()

Empty DataFrame
Columns: [order_id, payment_sequential, duplicates]
Index: []

In [165]:
con.execute("""
    SELECT customer_id, COUNT(*) AS duplicates
    FROM raw.olist_customers_dataset
    GROUP BY customer_id
    HAVING COUNT(*) > 1;
""").fetchdf()

Empty DataFrame
Columns: [customer_id, duplicates]
Index: []

In [166]:
con.execute("""
    SELECT product_id, COUNT(*) AS duplicates
    FROM raw.olist_products_dataset
    GROUP BY product_id
    HAVING COUNT(*) > 1;
""").fetchdf()

Empty DataFrame
Columns: [product_id, duplicates]
Index: []

## Existing orders

In [167]:
con.execute("""
    SELECT COUNT(*) AS order_ids_no_order
    FROM raw.olist_order_items_dataset i
    LEFT JOIN raw.olist_orders_dataset o USING (order_id)
    WHERE o.order_id IS NULL;
""").fetchdf()

   order_ids_no_order
0                   0

In [168]:
con.execute("""
    SELECT COUNT(*) AS product_ids_no_product
    FROM raw.olist_order_items_dataset i
    LEFT JOIN raw.olist_products_dataset p USING (product_id)
    WHERE p.product_id IS NULL;
""").fetchdf()

   product_ids_no_product
0                       0

In [169]:
con.execute("""
    SELECT COUNT(*) AS customer_ids_no_order
    FROM raw.olist_customers_dataset c
    LEFT JOIN raw.olist_orders_dataset o USING (customer_id)
    WHERE o.order_id IS NULL;
""").fetchdf()

   customer_ids_no_order
0                      0

## Unique Customers

In [170]:
con.execute("""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT customer_id) AS customer_ids,
        COUNT(DISTINCT customer_unique_id) AS actual_customers
    FROM raw.olist_customers_dataset;
""").fetchdf()

    rows  customer_ids  actual_customers
0  99441         99441             96096

In [171]:
con.execute("""
    SELECT customer_unique_id, COUNT(DISTINCT customer_id) AS customer_ids
    FROM raw.olist_customers_dataset
    GROUP BY customer_unique_id
    HAVING COUNT(DISTINCT customer_id) > 1
    ORDER BY customer_ids DESC;
""").fetchdf()

                    customer_unique_id  customer_ids
0     8d50f5eadf50201ccdcedfb9e2ac8455            17
1     3e43e6105506432c953e165fb2acf44c             9
2     1b6c7548a2a1f9037c1fd3ddfed95f33             7
3     6469f99c1f9dfae7733b25662e7f1782             7
4     ca77025e7201e3b30c44b472ff346268             7
...                                ...           ...
2992  40f4b191d404a10a6039af0b26dd62c7             2
2993  2d14556024f4bbe01f147576097c42fe             2
2994  d7a9f47a1c943e087a775dc2f9d43eb3             2
2995  01f2285f85a1c603eb7ef755ad311769             2
2996  e1cf735f320c9870c2046dbbc634fcec             2

[2997 rows x 2 columns]

## Translations

In [172]:
con.execute("""
    SELECT
        p.product_category_name,
        COUNT(*) AS products
    FROM raw.olist_products_dataset p
    LEFT JOIN raw.product_category_name_translation t
        USING (product_category_name)
    WHERE t.product_category_name IS NULL
    GROUP BY p.product_category_name
    ORDER BY products DESC;
""").fetchdf()

                           product_category_name  products
0                                            NaN       610
1  portateis_cozinha_e_preparadores_de_alimentos        10
2                                       pc_gamer         3

In [173]:
con.execute("""
    SELECT *
    FROM raw.olist_products_dataset
    WHERE product_category_name = 'pc_gamer'
""").fetchdf()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0105b5323d24fc655f73052694dbbb3a,pc_gamer,59,621,4,2839,19,16,18
1,6727051471a0fc4a0e7737b57bff2549,pc_gamer,60,1532,3,650,16,22,20
2,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,60,840,6,800,18,22,22

In [174]:
con.execute("""
    SELECT *
    FROM raw.product_category_name_translation
    WHERE product_category_name = 'pc_gamer'
""").fetchdf()

Empty DataFrame
Columns: [product_category_name, product_category_name_english]
Index: []

In [175]:
con.execute("""
    SELECT product_category_name, COUNT(*) AS translations
    FROM raw.product_category_name_translation
    GROUP BY product_category_name
    HAVING COUNT(*) > 1;
""").fetchdf()

Empty DataFrame
Columns: [product_category_name, translations]
Index: []

## items vs payments

In [176]:
con.execute("""
    WITH items AS (
        SELECT order_id, COUNT(*) AS number_items
        FROM raw.olist_order_items_dataset
        GROUP BY order_id
    ),
    payments AS (
        SELECT order_id, COUNT(*) AS number_payments
        FROM raw.olist_order_payments_dataset
        GROUP BY order_id
    )
    SELECT
        i.order_id,
        i.number_items,
        p.number_payments,
        i.number_items * p.number_payments AS rows_after_merge
    FROM items i
    JOIN payments p USING (order_id)
    WHERE i.number_items > 1
    AND p.number_payments > 1
    LIMIT 20;
""").fetchdf()

,order_id,number_items,number_payments,rows_after_merge
0,cf014dc8804713618176fc95af41b221,2,4,8
1,d4d8638eaddca23adbfdd1b383a5f15b,2,2,4
2,30afdf98bd76676a199127199643a168,2,2,4
3,70a272d1c01754b91a8709ae7efe27be,2,2,4
4,bfe53abc61788e6ed7f64c2d7ccb106c,2,2,4
5,d24e8541128cea179a11a65176e0a96f,2,2,4
6,fedcd9f7ccdc8cba3a18defedd1a5547,2,19,38
7,68986e4324f6a21481df4e6e89abcf01,2,12,24
8,669d4be1c2a2cab7e5ec040bf54c5d91,2,2,4
9,c8c4cee82cc04a8966a13f97e9366b82,2,2,4
10,54130db48a3d7ee5636ba18659ab73a8,2,2,4
11,0ea7c4f19490b13285f00729f7f9b276,2,2,4
12,9a8df1603191fe8fa15788692de6f4c3,2,2,4
13,3ff25314bbe9dc1ec7c983499bdff8f2,2,2,4
14,f45d4aa8bc99c39436fe3636932ea53f,2,2,4
15,21d032917e4ed1476f16ce92d0d8fdd4,2,2,4
16,3957b45bce42070cac232014ad4d001b,2,2,4
17,315f7759c3f6557f50e47798ccd673a3,2,2,4
18,3d177fa8a164dd0cb060f3051dc4ae8f,3,2,6
19,2a898874fbdeadc5df2ea8a0b01b85cb,2,3,6

## types, states and dates

In [177]:
con.execute("""
    SELECT
        TRY_CAST(price AS DECIMAL(12, 2)) AS price_num
    FROM raw.olist_order_items_dataset
    LIMIT 10;
""").fetchdf()

   price_num
0      58.90
1     239.90
2     199.00
3      12.99
4     199.90
5      21.90
6      19.90
7     810.00
8     145.95
9      53.99

In [178]:
con.execute("""
    SELECT
        COUNT(*) AS rows,
        SUM(CASE WHEN price IS NULL THEN 1 ELSE 0 END) AS null_values,
        SUM(CASE
            WHEN price IS NOT NULL
            AND TRY_CAST(price AS DECIMAL(12, 2)) IS NULL
            THEN 1 ELSE 0
        END) AS values_no_convertibles
    FROM raw.olist_order_items_dataset;
""").fetchdf()

     rows  null_values  values_no_convertibles
0  112650          0.0                     0.0

In [179]:
con.execute("""
    SELECT order_status, COUNT(*) AS orders
    FROM raw.olist_orders_dataset
    GROUP BY order_status
    ORDER BY orders DESC;
""").fetchdf()

  order_status  orders
0    delivered   96478
1      shipped    1107
2     canceled     625
3  unavailable     609
4     invoiced     314
5   processing     301
6      created       5
7     approved       2

In [180]:
con.execute("""
    SELECT
        COUNT(*) AS rows,
        SUM(CASE
            WHEN order_purchase_timestamp IS NOT NULL
            AND TRY_CAST(order_purchase_timestamp AS TIMESTAMP) IS NULL
            THEN 1 ELSE 0
        END) AS dates_no_convertibles,
        MIN(TRY_CAST(order_purchase_timestamp AS TIMESTAMP)) AS first_purchase,
        MAX(TRY_CAST(order_purchase_timestamp AS TIMESTAMP)) AS last_purchase
    FROM raw.olist_orders_dataset;
""").fetchdf()

    rows  dates_no_convertibles      first_purchase       last_purchase
0  99441                    0.0 2016-09-04 21:15:19 2018-10-17 17:30:18

## Model exploration

In [181]:
con.execute("""
    SELECT
        'dim_customers' AS table_name,
        COUNT(*) AS total_rows,
        COUNT(DISTINCT customer_id) AS unique_keys
    FROM modeled.dim_customers

    UNION ALL

    SELECT
        'dim_products',
        COUNT(*),
        COUNT(DISTINCT product_id)
    FROM modeled.dim_products

    UNION ALL

    SELECT
        'fact_orders',
        COUNT(*),
        COUNT(DISTINCT order_id)
    FROM modeled.fact_orders;
""").fetchdf()

      table_name  total_rows  unique_keys
0  dim_customers       99441        99441
1   dim_products       32951        32951
2    fact_orders       99441        99441

In [182]:
con.execute("""  
SELECT
    'fact_order_items' AS table_name,
    COUNT(*) AS total_rows,
    COUNT(DISTINCT (order_id, order_item_id)) AS unique_keys
FROM modeled.fact_order_items

UNION ALL

SELECT
    'fact_payments',
    COUNT(*),
    COUNT(DISTINCT (order_id, payment_sequential))
FROM modeled.fact_payments;
""").fetchdf()

         table_name  total_rows  unique_keys
0  fact_order_items      112650       112650
1     fact_payments      103886       103886

In [183]:
con.execute("""
SELECT
    'fact_orders.order_purchase_timestamp' AS column_name,
    COUNT(*) FILTER (
        WHERE order_purchase_timestamp IS NULL
    ) AS null_rows
FROM modeled.fact_orders

UNION ALL

SELECT
    'fact_orders.order_delivered_customer_date',
    COUNT(*) FILTER (
        WHERE order_delivered_customer_date IS NULL
    )
FROM modeled.fact_orders

UNION ALL

SELECT
    'fact_order_items.price',
    COUNT(*) FILTER (WHERE price IS NULL)
FROM modeled.fact_order_items

UNION ALL

SELECT
    'fact_order_items.freight_value',
    COUNT(*) FILTER (WHERE freight_value IS NULL)
FROM modeled.fact_order_items

UNION ALL

SELECT
    'fact_payments.payment_value',
    COUNT(*) FILTER (WHERE payment_value IS NULL)
FROM modeled.fact_payments

UNION ALL

SELECT
    'dim_products.product_weight_g',
    COUNT(*) FILTER (WHERE product_weight_g IS NULL)
FROM modeled.dim_products;
""").fetchdf()

                                 column_name  null_rows
0       fact_orders.order_purchase_timestamp          0
1  fact_orders.order_delivered_customer_date       2965
2                     fact_order_items.price          0
3             fact_order_items.freight_value          0
4                fact_payments.payment_value          0
5              dim_products.product_weight_g          2

In [184]:
con.execute("""
SELECT
    order_status,
    COUNT(*) AS orders_without_delivery_date
FROM modeled.fact_orders
WHERE order_delivered_customer_date IS NULL
GROUP BY order_status
ORDER BY orders_without_delivery_date DESC;
""").fetchdf()

  order_status  orders_without_delivery_date
0      shipped                          1107
1     canceled                           619
2  unavailable                           609
3     invoiced                           314
4   processing                           301
5    delivered                             8
6      created                             5
7     approved                             2

In [185]:
con.execute("""
SELECT
    order_id,
    order_status,
    order_purchase_timestamp,
    order_delivered_carrier_date,
    order_delivered_customer_date,
    order_estimated_delivery_date
FROM modeled.fact_orders
WHERE
    (order_status = 'delivered'
        AND order_delivered_customer_date IS NULL)
    OR
    (order_status = 'canceled'
        AND order_delivered_customer_date IS NOT NULL)
ORDER BY order_status, order_id;
""").fetchdf()

,order_id,order_status,order_purchase_timestamp,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,1950d777989f6a877539f53795b4c3c3,canceled,2018-02-19 19:48:52,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09
1,2c45c33d2f9cb8ff8b1c86cc28c11c30,canceled,2016-10-09 15:39:56,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08
2,65d1e226dfaeb8cdc42f665422522d14,canceled,2016-10-03 21:01:41,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25
3,770d331c84e5b214bd9dc70a10b829d0,canceled,2016-10-07 14:52:30,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29
4,8beb59392e21af5eb9547ae1a9938d06,canceled,2016-10-08 20:17:50,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30
5,dabf2b0e35b423f94618bf965fcb7514,canceled,2016-10-09 00:56:52,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30
6,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-03 09:28:00,NaT,2018-07-24
7,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-07-03 19:26:00,NaT,2018-07-19
8,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-30 18:12:23,NaT,2017-12-18
9,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,NaT,NaT,2017-06-23
10,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-03 13:57:00,NaT,2018-07-30
11,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-12 14:10:00,NaT,2018-06-26
12,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-03 13:57:00,NaT,2018-07-30
13,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-25 08:05:00,NaT,2018-07-16

In [186]:
con.execute("""
SELECT
    'orders_without_customer' AS check_name,
    COUNT(*) AS issue_count
FROM modeled.fact_orders o
LEFT JOIN modeled.dim_customers c
    ON o.customer_id = c.customer_id
WHERE c.customer_id IS NULL

UNION ALL

SELECT
    'items_without_order',
    COUNT(*)
FROM modeled.fact_order_items i
LEFT JOIN modeled.fact_orders o
    ON i.order_id = o.order_id
WHERE o.order_id IS NULL

UNION ALL

SELECT
    'items_without_product',
    COUNT(*)
FROM modeled.fact_order_items i
LEFT JOIN modeled.dim_products p
    ON i.product_id = p.product_id
WHERE p.product_id IS NULL

UNION ALL

SELECT
    'payments_without_order',
    COUNT(*)
FROM modeled.fact_payments p
LEFT JOIN modeled.fact_orders o
    ON p.order_id = o.order_id
WHERE o.order_id IS NULL;
""").fetchdf()

                check_name  issue_count
0  orders_without_customer            0
1      items_without_order            0
2    items_without_product            0
3   payments_without_order            0

# Close connection

In [187]:
con.close()